---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: logs-sync
  namespace: monitoring
spec:
  interval: 1m
  path: ./infrastructure/logs
  prune: true
  dependsOn:
    - name: monitoring-sync
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: monitoring-flux-infra
    namespace: flux-system
