---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "71.2.0"
  interval: 10m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: [ "/metadata/annotations/prometheus-operator-validated" ]
        target:
          kind: PrometheusRule
  valuesFrom:
    # Shared/base values for monitoring applications
    - kind: ConfigMap
      name: base-values
      valuesKey: kube-prometheus-stack-base-values.yaml
    # Additional configuration for dashboards, metrics, or infrastructure
    - kind: ConfigMap
      name: base-config
      valuesKey: kube-state-metrics-base-config.yaml
    # Environment-type values
    - kind: ConfigMap
      name: env-values
      valuesKey: kube-prometheus-stack-env-values.yaml
    # Project values
    - kind: ConfigMap
      name: project-values
      valuesKey: kube-prometheus-stack-project-values.yaml
