apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
configMapGenerator:
  - name: base-values
    files:
      - alloy-base-values.yaml=alloy/values.yaml
      - kube-prometheus-stack-base-values.yaml=kube-prometheus-stack/values.yaml
      - loki-base-values.yaml=loki/values.yaml
  - name: base-config
    files:
      - kube-state-metrics-base-config.yaml=kube-prometheus-stack/metrics.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomize.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - alloy
  - kube-prometheus-stack
  - loki
  - sources.yaml
