---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: project-sync
  namespace: monitoring
spec:
  interval: 10m0s
  path: ./examples/kind/monitoring
  postBuild:
    substitute:
      ALLOY_VERSION: "1.2.0"
      KUBE_PROMETHEUS_STACK_VERSION: "71.2.0"
      LOKI_VERSION: "6.33.0"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
