name: release-stack

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release-github:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Source repository
        uses: actions/checkout@v5
      - name: Create release
        run: |
          gh release create ${GITHUB_REF#refs/*/} \
          --notes-from-tag \
          --verify-tag
        env:
          GITHUB_TOKEN: ${{ github.token }}
