name: release-stack

on:
  push:
    branches:
      - main

jobs:
  release-github:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: digicatapult/shared-workflows/.github/workflows/release-github.yml@main
    permissions:
      contents: write
      pull-requests: read
    secrets: inherit
